__default__:
  account: YOUR_PI_GROUP   # replace with your Sherlock PI group (e.g. sjdavis)
  partition: serc
  email: YOUR_EMAIL        # replace with your email address
  walltime: 00:30:00   # time limit for each job
  cpus_per_task: 1   # number of cores per job
  chdir:
  output: logs/{rule}/log-%j.out
  error: logs/{rule}/errlog-%j.err

build_renewable_profiles:
  walltime: 06:00:00

add_electricity:
  walltime: 06:00:00

simplify_network:
  walltime: 09:00:00

cluster_network:
  walltime: 09:00:00

solve_network:
  walltime: '24:00:00'

solve_network_ab2383:
  walltime: '40:00:00'

solve_network_validation:
  walltime: 09:00:00

prepare_network:
  walltime: 01:00:00

add_extra_components:
  walltime: 01:00:00

add_demand:
  walltime: 02:00:00

build_bus_regions:
  walltime: 02:00:00

build_electrical_demand:
  walltime: 02:00:00

plot_statistics:
  walltime: 01:00:00

plot_network_maps:
  walltime: 01:00:00
